name: bitcoin_bip32_ng
version: 0.1.5
description: Library implementing Bitcoins BIP32 (Hierarchical Deterministic key derivation) specification in a Flutter friendly fashion.
homepage: https://github.com/sigrlami/bitcoin_bip32

# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  pointycastle: ^3.7.3
  base58check: ^2.0.0
  convert: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
